### ISSUE TITLE
Discard duplicate subscriptions

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Transport.Msmq#30]
Issue raised based on https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/o3UD8KD3xBc/rEV9NmmbAwAJ

There are several ways how the same subscription message can end up multiple times in the subscription queue, e.g. startup the publisher then startup the subscriber (which subscribed already once before). This doesn't cause any problems but it seems to cause confusion for users as they see the same subscription multiple times in the storage. Duplicate subscriptions should be removed at the next publisher restart though.

The current implementation always stores incoming subscriptions to the queue first, mostly to avoid any chance of message loss and drift between the inmemory and persisted subscriptions. It might be possible to check the loaded subscriptions before storing the message to avoid the duplicate subscription being stored.

**Comment by ramonsmits** [comment]
Currently, we only do dedupe on queue read. The current implementation of writing the subscription is fine. Only thing missing is that we should execute the dedupe logic in the queue after we have updated the in-memory state.

https://github.com/Particular/NServiceBus.Transport.Msmq/blob/31442b2b77e6f8c1410a561725e3ab5226b448e9/src/NServiceBus.Transport.Msmq/Persistence/SubscriptionStorage/MsmqSubscriptionStorage.cs#L95-L106

We only need to execute the Init logic.

## Always rebuild

Also, IMHO, we should not update the in memory state based on the message received. There should always be one source of truth and that is the subscription queue. When we receive the subscription event we should:

- Store subscription data
- Rebuild subscription data based on persistence

## Not caching subscriptions

Besides that, there are customer that use a single shared subscription queue where subscriptions might not be processed by a specific endpoint. For example, all AC's within a service share the same subscription storage. You don't know which AC processes the subscription but it could be that another AC would publish an event. Because other subscription persisters like SQL and NHibernate always query subscription persistence this would just work. This doesn't work for MSMQ subscription persistence because the state is always kept in memory.

@andreasohlund As discussed during the sync.

**Comment by andreasohlund** [comment]
>Because other subscription persisters like SQL and NHibernate always query subscription persistence this would just work. This doesn't work for MSMQ subscription persistence because the state is always kept in memory.

We could do a "refresh and deduplicate" periodically, that would solve the issue with other instances adding new subscribers to the queue?

**Comment by ramonsmits** [comment]
@andreasohlund We talked about my comment during the sync. Also take note of my "Not caching subscriptions". Do you want me to create a new issue for it or can we just use this issue?

**Comment by andreasohlund** [comment]
Lets use this issue for now

**Comment by ramonsmits** [comment]
Impact is very low, but probably also really easy to implement. Important to test with a shared subscription queue.

**Comment by ramonsmits** [comment]
In PR #152 we address this by keeping storage in sync at the cost of processing many subscribe/unsubscribe messages are a much lower rate as the current implementation is lazy.

The behavior isn't broken and decided to reject this PR.

Other alternatives were discussed like:

- Triggerered every time a (un)subscribe message is processed asynchronously from in-memory state. Potentially skipping unneeded rebuilds.
- Dedupe at a fixed timer
- Dedupe via "delayed event handling" after for example 15 seconds after the last received (un)subscribe message.

We didn't see value in any of these for now especially because (un)subscribe message rate is fairly low.
