### ISSUE TITLE
Queue permissions added by CreateQueue.ps1 are insufficient

### ISSUE THREAD

**Issue by agross** [Particular/NServiceBus.Transport.Msmq#69]
This is also referring back to #14.

While upgrading to NSB 7 I decided to go with the documented way of creating queues, i.e. running [`CreateQueue -QueueName foo -Account <my NSB host's identity>`](https://github.com/Particular/NServiceBus.Transport.Msmq/blob/dc67bc7e7528fc8731b875071cad736b01a8c08e/src/NServiceBus.Transport.Msmq/Scripts/CreateQueues.ps1).

The script added the permissions required for my service to send messages but left `Everyone` and `ANONYMOUS LOGIN` permissions in place. As soon as the host starts I see warnings like these:

```
DEBUG ort.Msmq.QueuePermissions - Checking if queue exists: TRITON1026\private$\GROSSWEBER.qa.ops.
DEBUG ort.Msmq.QueuePermissions - Verified that the queue: [TRITON1026\private$\GROSSWEBER.qa.ops] exists
WARN  ort.Msmq.QueuePermissions - Queue [private$\GROSSWEBER.qa.ops] is running with [Everyone] with AccessRights set to [GenericWrite]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
WARN  ort.Msmq.QueuePermissions - Queue [private$\GROSSWEBER.qa.ops] is running with [NT AUTHORITY\ANONYMOUS LOGON] with AccessRights set to [WriteMessage]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
```

In #14 I tried deleting the offending ACEs for `Everyone` and `ANONYMOUS LOGIN` but that makes the service itself unable to query the queue permissions because `CreateQueue` only adds permissions to send, peek and receive messages. The permission to query the queue's properties is not granted. Since the endpoint tries to do just that while starting up, successive endpoint startups will fail.

Please extend `CreateQueue` to include the `Get properties` permission required. The [documentation](https://docs.particular.net/transports/msmq/operations-scripting) is also missing this information.

**Comment by andreasohlund** [comment]
@agross thanks for reporting this, we will look into this and get back to you shortly

**Comment by andreasohlund** [comment]
@agross I've flagged this as a candidate for next release but we have no timeline at this stage.

We didn't deem this as a patch since the incorrect script just generates a WARN at startup.

To summarize the actions we need to take:

* Make sure the script doesn't give `Everyone` and `ANONYMOUS LOGIN` permissions
* Make sure that the script also gives `{service-account}` permissions to `Get properties`
* Update documentation as needed

Did I get that right?

**Comment by agross** [comment]
@andreasohlund 

Hi Andreas,

> Make sure the script doesn't give Everyone and ANONYMOUS LOGIN permissions

The script doesn't explicitly add these permissions, these are the OS defaults in workgroup mode. I'm fine with removing them myself, as removing them after queue creation may break assumptions about default queue permissions by other MSMQ users.

> Make sure that the script also gives {service-account} permissions to Get properties
> Update documentation as needed

Yes, this is exactly what I meant.

My goal would be that if I try to get rid of the warnings by removing the offending permissions from the queues NServiceBus is still be able to use the queue.

**Comment by andreasohlund** [comment]
>My goal would be that if I try to get rid of the warnings by removing the offending permissions from the queues NServiceBus is still be able to use the queue.

So you had to manually add `Get permission` right?

**Comment by agross** [comment]
> So you had to manually add Get Properties permission right?

Yes, exactly. My [deployment script](https://github.com/dnugleipzig/deploy) executes this custom installer to set the permissions such that the service (NSB Host) is able to start and I don't get warnings:

```powershell
. .\bin\NServiceBus.Transport.Msmq\CreateQueues.ps1
$Config.queues | ForEach-Object {
  $('Creating queue {0} for account {1}' -f $_, $ServiceIdentity) | Out-Host
  CreateQueue -QueueName $_ -Account $ServiceIdentity

  $('Fixing queue permissions of {0} for account {1}' -f $_, $ServiceIdentity) | Out-Host
  $QueuePath = '{0}\private$\{1}' -f $env:COMPUTERNAME, $_
  $Queue = New-Object System.Messaging.MessageQueue($QueuePath)

  $Queue.SetPermissions($ServiceIdentity, 'GetQueueProperties', 'Allow')
  $Queue.SetPermissions($(ConvertTo-UserName -Identity 'sid://WorldSid'), 'FullControl', 'Revoke')
  $Queue.SetPermissions($(ConvertTo-UserName -Identity 'sid://AnonymousSid'), 'FullControl', 'Revoke')
}
```

**Comment by agross** [comment]
@andreasohlund Yes, that sound correct, at least in Workgroup mode these permissions will be set according to [your docs](https://docs.particular.net/transports/msmq/#permissions).

The `RemoveAnonymous` switch should actually have on dash only, according to PowerShell conventions ;-)

**Comment by ramonsmits** [comment]
@andreasohlund Yeah, it seems like a good statement to add. Still not really fond on adding options to remove certain permissions as the user also then needs do ADD additional permissions and I would want to stay away from any permission management by us.  As shown by @agross it is easy to alter the permissions in scipts.

I would say, lets add that remark to the queue creation script and we could even list the queue permissions when done as text output.

**Comment by ramonsmits** [comment]
I've researched the permissions and @agross is right that it is required to have get property permissions due to `NServiceBus.Transport.Msmq.MessagePump.QueueIsTransactional()` which in my opinion should not be a requirement but an optional permission.

**Comment by agross** [comment]
> get property permission ... which in my opinion should not be a requirement but an optional permission.

Sorry, I don't understand.

Because NSB checks whether a queue is transactional, the permission is required. If NSB won't check then the permission would be optional. But I don't see how using NSB with non-transactional queues is something one would want or if that is even supported by NSB.

**Comment by ramonsmits** [comment]
@agross The permissions is required because of that check but it is not a mandatory check to have it running. 

That is why I mentioned in my opinion, it is not the current behavior.  I think this check should only be ran when the installers are executed with `.EnableInstallers()`.

For now we must make sure that the script needs updating for the current behavior of NServiceBus and potentially adjust behavior of the current NServiceBus.Transport.Msmq package.

What do you think @andreasohlund ?

**Comment by andreasohlund** [comment]
Not sure we should only execute the check on install since its meant to protect against misconfigured queue and since we're moving away from installers it seems like startup is the only place to do it?

That said we could make it best effort and just log "INFO - Endpoint didn't have permissions to verify queue transactionally. Please make sure that {queue name} is marked as transactional" ?

No matter what we need to release a new version of the transport since the script is bundled so I what do we do in the meantime?


Perhaps update [the doco](https://docs.particular.net/transports/msmq/operations-scripting#create-queues) to include the `Get properties` as well?

**Comment by ramonsmits** [comment]
Options:

1. Have the installers set the "Get Properties", maybe also needs to change the verification.
2. Have a fail-safe if the properties could not be retrieved.
